apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: noteverse-app
spec:
  project: default
  source:
    repoURL: "https://github.com/aadil611/noteverse-gitops.git"
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
